let cache=[];
async function requireAuth(){if(!sb)return;const {data}=await sb.auth.getSession();if(!data.session)location.href="login.html"}
async function renderAdmin(){cache=await getMatches();adminMatches.innerHTML=cache.map(m=>`<div class="admin-match"><span><b>${m.home} ${m.hs}-${m.as} ${m.away}</b><br><small class="muted">${m.league} · ${m.status}</small></span><span><button onclick="editScore(${m.id})">Edit</button><button class="danger" onclick="removeMatch(${m.id})">Delete</button></span></div>`).join("")}
matchForm.onsubmit=async e=>{e.preventDefault();await upsertMatch({id:Date.now(),league:league.value,home:home.value,away:away.value,hs:+homeScore.value,as:+awayScore.value,status:status.value,time:time.value||"TBD"});e.target.reset();homeScore.value=awayScore.value=0;renderAdmin()}
async function removeMatch(id){if(confirm("Delete this match?")){await deleteMatch(id);renderAdmin()}}
async function editScore(id){let m=cache.find(x=>x.id===id),s=prompt("Enter score",`${m.hs}-${m.as}`),p=s&&s.match(/(\d+)\s*-\s*(\d+)/);if(!p)return;m.hs=+p[1];m.as=+p[2];let st=prompt("Status: upcoming, live or finished",m.status);if(["upcoming","live","finished"].includes(st))m.status=st;await upsertMatch(m);renderAdmin()}
function bubble(t,c){chat.insertAdjacentHTML("beforeend",`<div class="bubble ${c}">${t}</div>`);chat.scrollTop=chat.scrollHeight}
async function runAI(t){const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:t})});const cmd=await r.json();if(!r.ok)throw Error(cmd.error||"AI error");if(cmd.action==="add_match"){await upsertMatch({id:Date.now(),home:cmd.home,away:cmd.away,league:cmd.league||"Football",hs:cmd.home_score||0,as:cmd.away_score||0,status:cmd.status||"upcoming",time:cmd.time||"TBD"});await renderAdmin()}else if(cmd.action==="update_match"){let m=cache.find(x=>x.home.toLowerCase().includes((cmd.home||"").toLowerCase())&&x.away.toLowerCase().includes((cmd.away||"").toLowerCase()));if(!m)throw Error("Match not found");if(cmd.home_score!=null)m.hs=cmd.home_score;if(cmd.away_score!=null)m.as=cmd.away_score;if(cmd.status)m.status=cmd.status;if(cmd.time)m.time=cmd.time;await upsertMatch(m);await renderAdmin()}return cmd.explanation||"Command processed."}
sendAI.onclick=async()=>{let t=aiInput.value.trim();if(!t)return;bubble(t,"user");aiInput.value="";try{bubble(await runAI(t),"bot")}catch(e){bubble(e.message,"bot")}};aiInput.onkeydown=e=>{if(e.key==="Enter")sendAI.click()};requireAuth().then(renderAdmin);
